LANGS = {
    "uz": {
        "welcome": "🎬 *MediaBot'ga xush kelibsiz!*\nFilm kodi yoki nomini yuboring.",
        "lang_set": "✅ Til o'rnatildi!",
        "cancelled": "❌ Bekor qilindi.",
        "not_admin": "🚫 Faqat adminlar uchun.",
        "no_permission": "🚫 Sizda bu amal uchun ruxsat yo'q.",
        "ping_reply": "🏓 Pong! `{ms}ms`",
        "invalid_code": "❌ Film topilmadi. Kodni yoki nomni tekshiring.",
        "movie_found": "🎬 *{title}*",
        "movie_added": "✅ Qo'shildi!\n🇺🇿 `{title_uz}`\n🇷🇺 `{title_ru}`\n🇬🇧 `{title_en}`\n🔑 Kod: `{code}`",
        "movie_deleted": "✅ O'chirildi.",
        "movie_not_found": "❌ Topilmadi.",
        "delete_confirm": "🗑 *{title}* ni o'chirishni tasdiqlaysizmi?",
        "delete_cancelled": "❌ Bekor qilindi.",
        "search_results": "🔍 *Qidiruv natijalari:*\nBirini tanlang:",
        "search_not_found": "❌ *{query}* bo'yicha hech narsa topilmadi.",
        "serial_found": "📺 *{title}*\nQaysi qismni ko'rmoqchisiz?",
        "serial_added": "✅ Serial qo'shildi!\n🇺🇿 `{title_uz}`\n🇷🇺 `{title_ru}`\n🇬🇧 `{title_en}`\n🔑 Kod: `{code}`",
        "serial_episode_added": "✅ {episode}-qism qo'shildi!",
        "serial_no_episodes": "❌ Bu serialda hali qismlar yo'q.",
        "serial_episode_not_found": "❌ Qism topilmadi.",
        "join_required": "⚠️ Quyidagi kanallarga qo'shiling:",
        "not_member": "⚠️ Siz hali kanalga qo'shilmagansiz.",
        "support_not_set": "ℹ️ Qo'llab-quvvatlash xabari o'rnatilmagan.",
        "broadcast_done": "✅ Xabar {count} foydalanuvchiga yuborildi.",
        "btn_enter_code": "🔑 Kod kiritish",
        "btn_search": "🔍 Qidirish",
        "btn_support": "📞 Qo'llab-quvvatlash",
        "btn_language": "🌐 Til",
        "send_search_query": "🔍 Film yoki serial nomini yuboring:\n\n/cancel bekor qilish uchun",
        "send_code_prompt": "🔑 Film kodini yuboring:\n\n/cancel bekor qilish uchun",
        "flood_warning": "⏳ Iltimos, biroz kuting...",
        "konami_activated": "🎮 *Yashirin rejim faollashtirildi!*\n\nSiz o'yin kodini topdingiz 👾\nTabriklaymiz, hacker! 😈\n\n🔓 Maxfiy kod ochildi — uni bilib oling!",
        "konami_used": "😏 Allaqachon topgansiz buni...",
        "matrix_msg": "🐇 *Follow the white rabbit...*\n\n`Wake up, Neo...`\n`The Matrix has you...`\n\nQizil yoki ko'k tabletka? 💊",
        "matrix_used": "🤖 Siz allaqachon haqiqatni bilasiz...",
        "matrix_reveal": "🔴 *Qizil tabletka tanladingiz...*\n\nBot yaratuvchisi: *@dragnzxm*\nYordamchi AI: *Claude (Anthropic)*\n\n`The Matrix has you... but we set you free.` 🕊",
        "bypass_activated": "🔓 *VIP rejim faollashtirildi!*\nSiz maxsus foydalanuvchisiz 😎",
        "bypass_already": "😎 Siz allaqachon VIP foydalanuvchisiz!",
    },
    "ru": {
        "welcome": "🎬 *Добро пожаловать в MediaBot!*\nОтправьте код или название фильма.",
        "lang_set": "✅ Язык установлен!",
        "cancelled": "❌ Отменено.",
        "not_admin": "🚫 Только для администраторов.",
        "no_permission": "🚫 У вас нет прав для этого.",
        "ping_reply": "🏓 Понг! `{ms}ms`",
        "invalid_code": "❌ Фильм не найден. Проверьте код или название.",
        "movie_found": "🎬 *{title}*",
        "movie_added": "✅ Добавлено!\n🇺🇿 `{title_uz}`\n🇷🇺 `{title_ru}`\n🇬🇧 `{title_en}`\n🔑 Код: `{code}`",
        "movie_deleted": "✅ Удалено.",
        "movie_not_found": "❌ Не найдено.",
        "delete_confirm": "🗑 Удалить *{title}*?",
        "delete_cancelled": "❌ Отменено.",
        "search_results": "🔍 *Результаты поиска:*\nВыберите один:",
        "search_not_found": "❌ По запросу *{query}* ничего не найдено.",
        "serial_found": "📺 *{title}*\nКакую серию хотите посмотреть?",
        "serial_added": "✅ Сериал добавлен!\n🇺🇿 `{title_uz}`\n🇷🇺 `{title_ru}`\n🇬🇧 `{title_en}`\n🔑 Код: `{code}`",
        "serial_episode_added": "✅ Серия {episode} добавлена!",
        "serial_no_episodes": "❌ В этом сериале ещё нет серий.",
        "serial_episode_not_found": "❌ Серия не найдена.",
        "join_required": "⚠️ Вступите в следующие каналы:",
        "not_member": "⚠️ Вы ещё не вступили в канал.",
        "support_not_set": "ℹ️ Сообщение поддержки не установлено.",
        "broadcast_done": "✅ Рассылка отправлена {count} пользователям.",
        "btn_enter_code": "🔑 Ввести код",
        "btn_search": "🔍 Поиск",
        "btn_support": "📞 Поддержка",
        "btn_language": "🌐 Язык",
        "send_search_query": "🔍 Отправьте название фильма или сериала:\n\n/cancel для отмены",
        "send_code_prompt": "🔑 Отправьте код фильма:\n\n/cancel для отмены",
        "flood_warning": "⏳ Пожалуйста, подождите...",
        "konami_activated": "🎮 *Скрытый режим активирован!*\n\nВы нашли секретный код 👾\nПоздравляем, хакер! 😈\n\n🔓 Секретный код открыт — узнайте его!",
        "konami_used": "😏 Вы уже нашли это раньше...",
        "matrix_msg": "🐇 *Follow the white rabbit...*\n\n`Wake up, Neo...`\n`The Matrix has you...`\n\nКрасная или синяя таблетка? 💊",
        "matrix_used": "🤖 Вы уже знаете правду...",
        "matrix_reveal": "🔴 *Вы выбрали красную таблетку...*\n\nСоздатель бота: *@dragnzxm*\nПомощник AI: *Claude (Anthropic)*\n\n`The Matrix has you... but we set you free.` 🕊",
        "bypass_activated": "🔓 *VIP режим активирован!*\nВы особенный пользователь 😎",
        "bypass_already": "😎 Вы уже VIP пользователь!",
    },
    "en": {
        "welcome": "🎬 *Welcome to MediaBot!*\nSend a movie code or name to get started.",
        "lang_set": "✅ Language set!",
        "cancelled": "❌ Cancelled.",
        "not_admin": "🚫 Admins only.",
        "no_permission": "🚫 You don't have permission for this.",
        "ping_reply": "🏓 Pong! `{ms}ms`",
        "invalid_code": "❌ Movie not found. Check the code or name.",
        "movie_found": "🎬 *{title}*",
        "movie_added": "✅ Added!\n🇺🇿 `{title_uz}`\n🇷🇺 `{title_ru}`\n🇬🇧 `{title_en}`\n🔑 Code: `{code}`",
        "movie_deleted": "✅ Deleted.",
        "movie_not_found": "❌ Not found.",
        "delete_confirm": "🗑 Delete *{title}*?",
        "delete_cancelled": "❌ Cancelled.",
        "search_results": "🔍 *Search results:*\nChoose one:",
        "search_not_found": "❌ Nothing found for *{query}*.",
        "serial_found": "📺 *{title}*\nWhich episode do you want to watch?",
        "serial_added": "✅ Serial added!\n🇺🇿 `{title_uz}`\n🇷🇺 `{title_ru}`\n🇬🇧 `{title_en}`\n🔑 Code: `{code}`",
        "serial_episode_added": "✅ Episode {episode} added!",
        "serial_no_episodes": "❌ No episodes yet.",
        "serial_episode_not_found": "❌ Episode not found.",
        "join_required": "⚠️ Please join the following channels:",
        "not_member": "⚠️ You haven't joined the channel yet.",
        "support_not_set": "ℹ️ Support message not set yet.",
        "broadcast_done": "✅ Message sent to {count} users.",
        "btn_enter_code": "🔑 Enter Code",
        "btn_search": "🔍 Search",
        "btn_support": "📞 Support",
        "btn_language": "🌐 Language",
        "send_search_query": "🔍 Send movie or serial name:\n\n/cancel to stop",
        "send_code_prompt": "🔑 Send the movie code:\n\n/cancel to stop",
        "flood_warning": "⏳ Please wait a moment...",
        "konami_activated": "🎮 *Secret mode activated!*\n\nYou found the secret code 👾\nCongrats, hacker! 😈\n\n🔓 Secret code unlocked — find it out!",
        "konami_used": "😏 You already found this one...",
        "matrix_msg": "🐇 *Follow the white rabbit...*\n\n`Wake up, Neo...`\n`The Matrix has you...`\n\nRed or blue pill? 💊",
        "matrix_used": "🤖 You already know the truth...",
        "matrix_reveal": "🔴 *You chose the red pill...*\n\nBot creator: *@dragnzxm*\nAI assistant: *Claude (Anthropic)*\n\n`The Matrix has you... but we set you free.` 🕊",
        "bypass_activated": "🔓 *VIP mode activated!*\nYou are a special user 😎",
        "bypass_already": "😎 You're already a VIP user!",
    },
}


def get_text(lang, key, **kwargs):
    text = LANGS.get(lang, LANGS["uz"]).get(key, key)
    return text.format(**kwargs) if kwargs else text
